RyanBloger/BlogProject/urls.py
from django.conf.urls import url, include
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

import xadmin
from BlogProject.views import HomeView
from articles.models import Articles

info_dict = {
    'queryset': Articles.objects.all(),
    'date_field': 'modify_time',
}

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^tags/$', TemplateView.as_view(template_name='tags.html'), name='tags'),
    #
    url(r'^blog/', include('articles.urls', namespace='blog')),
    url(r'^haystack_search/', include('haystack.urls')),
    #
    # # 配置上传文件的访问处理函数
    # url('^media/(?P<path>.*)/$', serve, {'document_root': MEDIA_ROOT})
    # the sitemap
    url(r'sitemap.xml', sitemap,
        {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'mdeditor/', include('mdeditor.urls')),
]

RyanBloger/apps/articles/urls.py
from django.conf.urls import url

from articles.views import ArticleDetailView, ArchiveView, AllArticlesByCategoryView, AllArticleByTagView, \
    AboutMeView, IndexView, ProjectView, AllTagsView, AllCategorysView, search

__author__ = 'ryanhuen'
__data__ = '18-3-26 下午4:20'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^article/(?P<article_id>\d+)/$', ArticleDetailView.as_view(), name='article'),
    url(r'^archives/$', ArchiveView.as_view(), name='archives'),
    url(r'^categorys/', AllCategorysView.as_view(), name='categorys'),
    url(r'^category/(?P<category_name>\w+)$', AllArticlesByCategoryView.as_view(), name='category'),
    url(r'^tags/', AllTagsView.as_view(), name='tags'),
    url(r'^tag/(?P<tag_name>\w+)$', AllArticleByTagView.as_view(), name='tag'),
    url(r'^about/$', AboutMeView.as_view(), name='about'),
    url(r'^project/$', ProjectView.as_view(), name='project'),
    url('content.json/', search, name='search'),

]
app_name = 'articles'

RyanBloger/templates/search/search.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load highlight %}
{% block custom_js %}
    <script>
        var yiliaConfig = {
            rootUrl: "{% static '' %}",
            fancybox: true,
            animate: true,
            isHome: true,
            isPost: false,
            isArchive: false,
            isTag: false,
            isCategory: false,
            open_in_new: false
        }
    </script>
{% endblock %}
{% block content_area %}
    {% if query %}
        {% for article in page.object_list %}
            <article id="{% url 'blog:article' article.object.id %}" class="article article-type-post" itemscope
                     itemprop="blogPost">
                <div class="article-meta">
                    <a href="{% url 'blog:article' article.object.id %}" class="article-date">
                        <time datetime="{{ article.object.public_time|date:'c' }}"
                              itemprop="datePublished">{{ article.object.public_time|date:'o-g-j H:i' }}</time>
                    </a>
                </div>
                <div class="article-inner">
                    <input type="hidden" class="isFancy"/>
                    <header class="article-header">
                        <h1 itemprop="name">
                            <a class="article-title"
                               href="{% url 'blog:article' article.object.id %}">{% highlight article.object.title with query %}</a>
                        </h1>
                    </header>
                    <div class="article-entry" itemprop="articleBody">
                        {#                        {{ article.object.summary|safe }}#}
                        {% highlight article.object.content with query max_length 300 %}
                    </div>
                    <div class="article-info article-info-index">
                        <div class="article-category category_cloud">
                            <a class="article-category-link"
                               href="{% url 'blog:category' article.object.category.name %}">{{ article.object.category.name }}</a>
                        </div>
                        <div class="article-tag tagcloud">
                            <ul class="article-tag-list">
                                <li class="article-tag-list-item">{% for tag in article.object.tags.all %}
                                    <a class="article-tag-list-link"
                                       href="{% url 'blog:tag' tag.name %}">{{ tag.name }}</a>{% endfor %}</li>
                            </ul>
                        </div>
                        <p class="article-more-link">
                            <a href="{% url 'blog:article' article.object.id %}#more">查看更多 >></a>
                        </p>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </article>
        {% endfor %}
    {% endif %}

    <nav id="page-nav">
        {% if page.has_previous %}
            <a class="extend prev" rel="prev" href="?q={{ query }}&amp;page={{ page.previous_page_number }}">&laquo;
                Prev</a>
        {% endif %}
        <span class="space">&hellip;</span>
        {% if page.has_next %}
            <a class="extend next" rel="next" href="?q={{ query }}&amp;page={{ page.next_page_number }}">Next
                &raquo;</a>
        {% endif %}
    </nav>

{% endblock %}