RyanBloger/BlogProject/urls.py
from django.conf.urls import url, include
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

import xadmin
from BlogProject.views import HomeView
from articles.models import Articles

info_dict = {
    'queryset': Articles.objects.all(),
    'date_field': 'modify_time',
}

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^tags/$', TemplateView.as_view(template_name='tags.html'), name='tags'),
    #
    url(r'^blog/', include('articles.urls', namespace='blog')),
    url(r'^haystack_search/', include('haystack.urls')),
    #
    # # 配置上传文件的访问处理函数
    # url('^media/(?P<path>.*)/$', serve, {'document_root': MEDIA_ROOT})
    # the sitemap
    url(r'sitemap.xml', sitemap,
        {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'mdeditor/', include('mdeditor.urls')),
]

RyanBloger/apps/articles/urls.py
from django.conf.urls import url

from articles.views import ArticleDetailView, ArchiveView, AllArticlesByCategoryView, AllArticleByTagView, \
    AboutMeView, IndexView, ProjectView, AllTagsView, AllCategorysView, search

__author__ = 'ryanhuen'
__data__ = '18-3-26 下午4:20'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^article/(?P<article_id>\d+)/$', ArticleDetailView.as_view(), name='article'),
    url(r'^archives/$', ArchiveView.as_view(), name='archives'),
    url(r'^categorys/', AllCategorysView.as_view(), name='categorys'),
    url(r'^category/(?P<category_name>\w+)$', AllArticlesByCategoryView.as_view(), name='category'),
    url(r'^tags/', AllTagsView.as_view(), name='tags'),
    url(r'^tag/(?P<tag_name>\w+)$', AllArticleByTagView.as_view(), name='tag'),
    url(r'^about/$', AboutMeView.as_view(), name='about'),
    url(r'^project/$', ProjectView.as_view(), name='project'),
    url('content.json/', search, name='search'),

]
app_name = 'articles'

RyanBloger/templates/google09b8293c88584376.html
google-site-verification: google09b8293c88584376.html

RyanBloger/templates/home.html
{% load staticfiles %}
{% load blog_tags %}
{% site_config as SITE_CONFIGS %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>{{ SITE_CONFIGS.Name }} - {{ SITE_CONFIGS.Title }}</title>
    <meta name="keywords" content="Bgods,Python">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon_32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon_16x16.png' %}">

    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">
    <meta name="msapplication-TileColor" content="#f24e32">
    <meta name="theme-color" content="#FFFFFF">
    <meta name="google-site-verification" content="5TfFdrbKmOmDwq8kDEkfeTlUiCPSB-XD3s9-Y05uJlo" />


    <link rel="stylesheet" href="{% static 'css/index.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/APlayer.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">

    <script async="" src="{% static 'js/busuanzi.pure.mini.js' %}"></script>
    <script src="{% static 'js/APlayer.min.js' %}"></script>
    <script src="{% static 'js/Meting.min.js' %}"></script>
    <script src="{% static 'js/vue.min.js' %}"></script>
    <script>Vue.config.productionTip = !1, window.PAGE_TYPE = ""</script>

</head>

<body>
<div id="mobile-bar" class="top">
    <a class="menu-button fas fa-bars"></a>
    <a class="logo" href="{% url 'home' %}"></a>
</div>
<div id="header">
    <a id="logo" href="{% url 'home' %}">
        <img src="{% static 'images/favicon.png' %}">
        <span>{{ SITE_CONFIGS.Name }}</span>
    </a>
    <ul id="nav">
        <li class="nav-dropdown-container more">
            <a class="nav-link"><i class="fas fa-ellipsis-v fa-fw"></i>&nbsp;更多</a>
            <ul class="nav-dropdown">
                <li>
                    <ul>
                        <li><a class="nav-link" href="/xadmin"><i class="fas fa-user-md fa-fw"></i>&nbsp;XAdmin</a></li>
                    </ul>
                </li>
                <li><h4></h4></li>
                <li>
                    <ul>
                        <li><a class="nav-link" target="_blank" href="https://github.com/RyanHuen"
                               rel="external nofollow noopener noreferrer"><i class="fab fa-github fa-fw"></i>&nbsp;Github</a>
                        </li>
                        <li><a class="nav-link" target="_blank" href="mailto:ryanhuenwork@163.com"><i
                                class="fas fa-envelope fa-fw"></i>&nbsp;Email</a></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</div>

<div class="sidebar">
    <div class="sidebar-inner-index">
        <ul class="main-menu"><br>
            <h2><a href="{% url 'home' %}">{{ SITE_CONFIGS.Name }}</a></h2>
            <li class="nav-dropdown-container more">
                <a class="nav-link"><i class="fas fa-ellipsis-v fa-fw"></i>&nbsp;更多</a>
                <ul class="nav-dropdown">
                    <li>
                        <ul>
                            <li><a class="nav-link" href="/xadmin"><i class="fas fa-user-md fa-fw"></i>&nbsp;XAdmin</a>
                            </li>
                        </ul>
                    </li>
                    <li><h4></h4></li>
                    <li>
                        <ul>
                            <li><a class="nav-link" target="_blank" href="https://github.com/RyanHuen"
                                   rel="external nofollow noopener noreferrer"><i class="fab fa-github fa-fw"></i>&nbsp;Github</a>
                            </li>
                            <li><a class="nav-link" target="_blank" href="mailto:ryanhuenwork@163.com"><i
                                    class="fas fa-envelope fa-fw"></i>&nbsp;Email</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

<div id="hero">
    <div class="inner">
        <div class="left"><img class="hero-logo" src="{% static 'images/avatar.png' %}" alt="avatar"></div>
        <div class="right">
            <h2 class="vue">{{ SITE_CONFIGS.Name }}</h2>
            <div class="home-nav">
                <ul class="pure">
                    <li><a href="{% url 'blog:project' %}"><i class="fas fa-flask"></i>项目</a></li>
                    <li><a href="{% url 'blog:index' %}"><i class="fas fa-rss"></i>博客</a></li>
                </ul>
                <ul class="pure">
                    <li><a href="{% url 'blog:archives' %}"><i class="fas fa-archive"></i>归档</a></li>
                    <li><a href="{% url 'blog:about' %}"><i class="fas fa-user"></i>关于</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="posts">
    <div class="inner">


    </div>
</div>

<div id="video-modal" class="modal">
    <div class="video-space" style="padding:56.25% 0 0 0;position:relative"></div>
</div>
<script>!function () {
    var e = !1;
    window.addEventListener("scroll", function () {
        165 < window.pageYOffset && !e ? (e = !0, document.getElementById("mobile-bar").classList.remove("top")) : window.pageYOffset <= 165 && e && (e = !1, document.getElementById("mobile-bar").classList.add("top"))
    })
}()</script>

<!-- footer -->
{% include 'blog/footer.html' %}

<script src="{% static 'js/css.escape.js' %}"></script>
<script src="{% static 'js/fastclick.min.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>

<script>document.addEventListener("DOMContentLoaded", function () {
    FastClick.attach(document.body)
}, !1)</script>

</body>

</html>